# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'Tabla.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
#
# Creado por Anthoni Portocarrero Rodriguez en su totalidad

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1112, 789)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1111, 791))
        self.frame.setStyleSheet("\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(310, 40, 691, 91))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 281, 331))
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../Desktop/diseño/xdddd.svg"))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(340, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(340, 210, 91, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(340, 280, 91, 41))
        self.label_7.setObjectName("label_7")
        self.name = QtWidgets.QLineEdit(self.frame)
        self.name.setGeometry(QtCore.QRect(440, 154, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setStyleSheet("border-color: rgb(18, 154, 168);")
        self.name.setText("")
        self.name.setObjectName("name")
        self.lastname = QtWidgets.QLineEdit(self.frame)
        self.lastname.setGeometry(QtCore.QRect(440, 220, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lastname.setFont(font)
        self.lastname.setStyleSheet("border-color: rgb(18, 154, 168);")
        self.lastname.setText("")
        self.lastname.setObjectName("lastname")
        self.dni = QtWidgets.QLineEdit(self.frame)
        self.dni.setGeometry(QtCore.QRect(440, 280, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dni.setFont(font)
        self.dni.setStyleSheet("border-color: rgb(18, 154, 168);")
        self.dni.setText("")
        self.dni.setObjectName("dni")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 420, 464, 289))
        self.calendarWidget.setObjectName("calendarWidget")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(540, 500, 131, 31))
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(540, 610, 131, 31))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.btnContrato = QtWidgets.QPushButton(self.frame)
        self.btnContrato.setGeometry(QtCore.QRect(540, 450, 131, 41))
        self.btnContrato.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.btnContrato.setObjectName("btnContrato")
        self.btnInicial = QtWidgets.QPushButton(self.frame)
        self.btnInicial.setGeometry(QtCore.QRect(540, 560, 131, 41))
        self.btnInicial.setStyleSheet("background-color: rgb(88, 255, 191);\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.btnInicial.setObjectName("btnInicial")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(740, 450, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(740, 500, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.importe = QtWidgets.QLineEdit(self.frame)
        self.importe.setGeometry(QtCore.QRect(840, 450, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.importe.setFont(font)
        self.importe.setStyleSheet("border-color: rgb(18, 154, 168);")
        self.importe.setText("")
        self.importe.setObjectName("importe")
        self.inicial = QtWidgets.QLineEdit(self.frame)
        self.inicial.setGeometry(QtCore.QRect(840, 500, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inicial.setFont(font)
        self.inicial.setStyleSheet("border-color: rgb(18, 154, 168);")
        self.inicial.setText("")
        self.inicial.setObjectName("inicial")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(750, 580, 119, 23))
        self.radioButton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(890, 580, 119, 23))
        self.radioButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(830, 280, 131, 31))
        self.comboBox.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.btnCalcular = QtWidgets.QPushButton(self.frame)
        self.btnCalcular.setGeometry(QtCore.QRect(750, 640, 261, 51))
        self.btnCalcular.setStyleSheet("background-color: #4CAF50;\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"color:rgb(228, 234, 255);\n"
"")
        self.btnCalcular.setObjectName("btnCalcular")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(30, 355, 981, 41))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setEnabled(False)
        self.label_10.setGeometry(QtCore.QRect(10, 730, 1091, 41))
        self.label_10.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 4);")
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Tabla de Amortización</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Nombre:</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Apellido:</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">DNI:</span></p></body></html>"))
        self.btnContrato.setText(_translate("Dialog", "Fecha Contrato"))
        self.btnInicial.setText(_translate("Dialog", "Fecha Inicial"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Importe:</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Inicial:</span></p></body></html>"))
        self.radioButton.setText(_translate("Dialog", "Soles"))
        self.radioButton_2.setText(_translate("Dialog", "Dolares"))
        self.comboBox.setItemText(0, _translate("Dialog", "Proyecto"))
        self.comboBox.setItemText(1, _translate("Dialog", "Olivar"))
        self.comboBox.setItemText(2, _translate("Dialog", "Oasis"))
        self.comboBox.setItemText(3, _translate("Dialog", "Apolo"))
        self.comboBox.setItemText(4, _translate("Dialog", "Falcon"))
        self.btnCalcular.setText(_translate("Dialog", "Calcular"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Aqui va un texto de error</p></body></html>"))
        self.label_10.setVisible(False)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

